### ISSUE TITLE
'grunt-angular-service' is not in the npm registry.

### ISSUE THREAD

**Issue by amiiit** [obibring/grunt-angular-service#1]
I've tried the following:

$ npm install grunt-angular-service --save-dev

and got:

npm ERR! 404 404 Not Found: grunt-angular-service

Thanks

**Comment by obibring** [comment]
@amitit, I haven't published the repo yet to NPM. Will do so in the coming days and let you know.

**Comment by amiiit** [comment]
sure, thanks for the good work. looking forward to 'npm install' it (;

**Comment by obibring** [comment]
@amitit, sorry for the delay. Everything has been updated and published to the repo. Would love to hear your feedback. Thanks!

**Comment by amiiit** [comment]
thanks!
