### ISSUE TITLE
ngservice not working with d3.js

### ISSUE THREAD

**Issue by amiiit** [obibring/grunt-angular-service#4]
Hi!

I'm trying to wrap d3.js as a service. The library as the following format:

(!function(){
 //... d3 code ...
}())

neither of the export-strategies succeeds with delivering the content of the library. They either deliver true, undefinied, or Object {}

I'd be glad for some help, if you could

thanks for the good work, this is an important thing  (;

Amit.

**Comment by obibring** [comment]
@amitit, I tested d3 locally and it works for me using the `node` `exportStrategy`:

``` javascript
    ngservice: {
      d3: {
        exportStrategy: 'node',
        module: 'd3',
        defineModule: true,
        name: 'd3',
        files: {
          'tmp/ngd3.js': ['test/lib/d3/d3.js']
        }   
      },  
    }   
```

Can you give me some more details about the issues you're seeing?
