### ISSUE TITLE
Object has no method 'charAt'

### ISSUE THREAD

**Issue by juanmanuelarias** [obibring/grunt-angular-service#5]
When calling **grunt ngservice** I'm getting the following error:

```
Warning: Object function (data) {
      return render.call(this, data, _);
    } has no method 'charAt' Use --force to continue.
```

After a lot of debugging, I realized that the problem is on the dependencies. If I remove the `^` in the dependencies inside the package.json, the problem is resolved:

```
"dependencies": {
    "grunt-jsbeautifier": "0.2.7",
    "js-beautify": "1.5.1",
    "underscore": "1.6.0"
  },
```

**Comment by obibring** [comment]
Thanks for your help! I'll have a look.

**Comment by mjmendo** [comment]
I am getting the same error. The fix mentioned by [juanmanuelarias](https://github.com/juanmanuelarias) works.

**Comment by obibring** [comment]
Fixed. Closing the issue. If it persists, please reopen. Thanks.
